// Generated by https://flutterstudio.app/

import 'package:flutter/material.dart';
  final ThemeData myTheme = ThemeData(
    primarySwatch: Colors.pink,
    primaryColor: const Color(0xFFe91e63),
    accentColor: const Color(0xFFe91e63),
    canvasColor: const Color(0xFFfafafa),
    fontFamily: 'Roboto',
  );
