// Generated by https://flutterstudio.app/

import 'package:flutter/material.dart';

final ThemeData myTheme = ThemeData.from(
    colorScheme: ColorScheme.fromSeed(
        seedColor: Colors.pink,
        secondary: Colors.white,
    )
);
