// Generated by https://flutterstudio.app/

import 'package:flutter/material.dart';

const MaterialColor _mainColor = Colors.pink;

final ThemeData lightTheme = ThemeData.from(
    useMaterial3: true,
    colorScheme: ColorScheme.fromSeed(seedColor: _mainColor)
  // ColorScheme.fromSwatch(
  //   primarySwatch: Colors.pink,
  //   accentColor: Colors.white,
  //   backgroundColor: Colors.white,
  //   brightness: Brightness.light,
  // ),
)
    .copyWith(indicatorColor: Colors.pink)
;

final ThemeData darkTheme = ThemeData.from(
    useMaterial3: true,
    colorScheme: ColorScheme.fromSeed(
        seedColor: _mainColor,
        brightness: Brightness.dark
    )
)
//   ColorScheme.fromSwatch(
//     primarySwatch: Colors.pink,
//     accentColor: Colors.white,
//     backgroundColor: Colors.black54,
//     brightness: Brightness.dark,
//   ),
// )
    .copyWith(indicatorColor: Colors.pink)
;
